Mvc.BondApp/Controllers/BondTypeInformationController.cs
using Mvc.BondApp;
using System.Linq;
using System.Web.Mvc;

namespace templateMvc.Controllers
{
    public class BondTypeInformationController : Controller
    {
        BondModel _context = new BondModel();
        // GET: BondTypeInformation
        public ActionResult ListOfBond()
        {
            var bonds = _context.BONDINFOes.ToList();
            return View(bonds);
        }

        // GET: BondTypeInformation/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BondTypeInformation/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BondTypeInformation/Create
        [HttpPost]
        public ActionResult Create(BONDINFO bondinfo)
        {
            try
            {
                // TODO: Add insert logic here

                _context.BONDINFOes.Add(bondinfo);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: BondTypeInformation/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BondTypeInformation/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: BondTypeInformation/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BondTypeInformation/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Mvc.BondApp/Views/BondTypeInformation/Create.cshtml
@model Mvc.BondApp.BONDINFO




@using (Html.BeginForm("Create", "BondTypeInformation", FormMethod.Post, new { @class = "form-horizontal", @id="bondTypeForm"}))
{
    <fieldset>
        <legend>Bond Type Information</legend>
        <div class="form-group">
            @Html.LabelFor(x => x.BONDCODE, "Bond Code", new { @class = "control-label col-sm-3" })

            <div class="col-sm-9">
                @Html.TextBoxFor(x => x.BONDCODE, new { @class = "form-control", @placeholder = "Bond Code" })
                @Html.ValidationMessageFor(x=>x.BONDCODE)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.BONDNAME, "Bond Name", new { @class = "control-label col-sm-3" })

            <div class="col-sm-9">
                @Html.TextBoxFor(x => x.BONDNAME, new { @class = "form-control", @placeholder = "Bond Name" })
                @Html.ValidationMessageFor(x => x.BONDNAME)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.BONDSNAME, "Bond Short Name", new { @class = "control-label col-sm-3" })

            <div class="col-sm-9">
                @Html.TextBoxFor(x => x.BONDSNAME, new { @class = "form-control", @placeholder = "Bond Short Name" })
                @Html.ValidationMessageFor(x=>x.BONDSNAME)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.CURRCODE, "Principal in Currency", new {@class = "control-label col-sm-3"})

            <div class="col-sm-9">
                @Html.TextBoxFor(x => x.CURRCODE, new {@class = "form-control", @placeholder = "Principal in Currency"})
                @Html.ValidationMessageFor(x=>x.CURRCODE)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.INTCURRCODE, "Interest in Currency", new {@class = "control-label col-sm-3"})

            <div class="col-sm-9">
                @Html.TextBoxFor(x => x.INTCURRCODE, new {@class = "form-control", @placeholder = "Interest in Curr."})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.DURATION, "Duration", new {@class = "control-label col-sm-3"})

            <div class="col-sm-9">
                @Html.TextBoxFor(x => x.DURATION, new {@class = "form-control", @placeholder = "Duration in YEAR"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.CRACCT, "Credit Account", new {@class = "control-label col-sm-3"})

            <div class="col-sm-9">
                @Html.TextBoxFor(x => x.CRACCT, new {@class = "form-control", @placeholder = "Credit Account"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.DRACCT, "Debit Account", new {@class = "control-label col-sm-3"})

            <div class="col-sm-9">
                @Html.TextBoxFor(x => x.DRACCT, new {@class = "form-control", @placeholder = "Debit Account"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.SCRIPLENGTH, "Script Length", new {@class = "control-label col-sm-3"})

            <div class="col-sm-9">
                @Html.TextBoxFor(x => x.SCRIPLENGTH, new {@class = "form-control", @placeholder = "Script Length"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.INSURANCE, "Total Insurance Slub", new {@class = "control-label col-sm-3"})

            <div class="col-sm-9">
                @Html.TextBoxFor(x => x.INSURANCE, new {@class = "form-control", @placeholder = "Total Insurance Slub"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.INSTDURATION, "Interest Duration", new {@class = "control-label col-sm-3"})

            <div class="col-sm-9">
                @Html.TextBoxFor(x => x.INSTDURATION, new {@class = "form-control", @placeholder = "Interest Duration"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.COMPOUNDINT, "Compound Interest Time", new { @class = "control-label col-sm-3" })

            <div class="col-sm-9">
                @Html.TextBoxFor(x => x.COMPOUNDINT, new { @class = "form-control", @placeholder = "Compound Interest Time (in Month)" })
            </div>
        </div>

        <div class="col-sm-12 col-sm-offset-8">
            <input class="btn btn-danger btn-sm" type="submit" name="SaveButton" value="Save"/>
            <input class="btn btn-danger btn-sm" type="button" onclick="FormResetFunction()" value="Reset form">
            @Html.ActionLink("List Of Bonds Available", "ListOfBond", "BondTypeInformation", new { @class = "btn btn-sm btn-danger" })
        </div>
   

        
    </fieldset>

}

<script>
  
        function FormResetFunction() {
         document.getElementById("bondTypeForm").reset();
        }
       

</script>

Mvc.BondApp/Views/BondTypeInformation/ListOfBond.cshtml
@model IEnumerable<Mvc.BondApp.BONDINFO>

@{
    ViewBag.Title = "ListOfBond";
}

<h2>List Of Bond</h2>

<p>
    @Html.ActionLink("Create New Bond", "Create","BondTypeInformation",new {@class="btn btn-sm btn-danger"})
</p>
<table class="table table-responsive table-bordered table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BONDNAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BONDSNAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CURRCODE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.INTCURRCODE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DURATION)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.CRACCT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DRACCT)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.SCRIPLENGTH)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.USERID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ENTRYDATE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TERMINAL)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.INSURANCE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.INSTDURATION)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.COMPOUNDINT)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.CERTIHEAD)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BONDNAME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BONDSNAME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CURRCODE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.INTCURRCODE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DURATION)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.CRACCT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DRACCT)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.SCRIPLENGTH)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.USERID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ENTRYDATE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TERMINAL)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.INSURANCE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.INSTDURATION)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.COMPOUNDINT)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.CERTIHEAD)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BONDCODE },new {@class="btn btn-xs btn-danger "}) 
            @Html.ActionLink("Details", "Details", new { id=item.BONDCODE },new {@class="btn btn-xs btn-danger "}) 
            @Html.ActionLink("Delete", "Delete", new { id=item.BONDCODE },new {@class="btn btn-xs btn-danger "})
        </td>
    </tr>
}

</table>