Mvc.BondApp/Controllers/CurrencyInformationController.cs
using Mvc.BondApp;
using System.Linq;
using System.Web.Mvc;

namespace templateMvc.Controllers
{
    public class CurrencyInformationController : Controller
    {

        BondModel _context = new BondModel();
        // GET: CurrencyInformation
        public ActionResult ListOfCurrency()
        {
            var currencyList = _context.CURRINFOes.ToList();
            return View(currencyList);
        }

        // GET: CurrencyInformation/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CurrencyInformation/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CurrencyInformation/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CurrencyInformation/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CurrencyInformation/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CurrencyInformation/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CurrencyInformation/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Mvc.BondApp/Views/CurrencyInformation/ListOfCurrency.cshtml
@model IEnumerable<Mvc.BondApp.CURRINFO>

@{
    ViewBag.Title = "Currency Info";
}

<h2>Currency Information</h2>

<p>
    @Html.ActionLink("Create New", "Create","CurrencyInformation",new {@class="btn btn-sm btn-danger"},new {})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Currency Code")
        </th>
        <th>
            @Html.DisplayName("Currency Name")
        </th>
        <th>
            @Html.DisplayName("Sign")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CURRCODE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CURRNAME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CURRSIGN)
        </td>
   
        <td>
            @Html.ActionLink("Edit", "Edit", new {id = item.CURRCODE}      ,new {@class="btn btn-xs btn-danger col-sm-1"} ) 
            @Html.ActionLink("Details", "Details", new {id = item.CURRCODE},new {@class="btn btn-xs btn-danger col-sm-1"} ) 
            @Html.ActionLink("Delete", "Delete", new {id = item.CURRCODE}  ,new {@class="btn btn-xs btn-danger col-sm-1"} )
        </td>
    </tr>
}

</table>